theme: jekyll-theme-minimal
title: Francesco's blog
author: Francesco Favatella

# description: Blog description


# pages to show on header
header_pages:
  - about.md

theme: minima

# default articles prefix
permalink: /articles/:title

collections:
  code-snippets:
    output: true
  english:
    output: true
  notes:
    output: true
    

defaults:
  - scope:
      path: ""
    values:
      layout: "tutorial"


# plugins used
plugins:
  - jekyll-feed

feed:
  path: feed.xml
