theme: jekyll-theme-minimal
title: Francesco's blog
# description: Blog description


# pages to show on header
header_pages:
  - about.md

theme: minima

# default articles prefix
permalink: /articles/:title

collections:
  code-snippets:
    output: true
  english:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "tutorial"
